#!/bin/bash

#SBATCH -N 1     # Uppercase N tells the scheduler to use a single compute node
#SBATCH -n 2   #  Use 12 cpu cores
#SBATCH --mem-per-cpu=4000  #  Use 4GB per core, or 48GB total
#SBATCH -p serial   # Run in the serial partition
#SBATCH -t 0-10:00   
#SBATCH -A user  
#SBATCH -o slurm.sambam_IT.out  
#SBATCH -e slurm.sambam_IT.err  
#SBATCH --mail-type=END,FAIL     
#SBATCH --mail-user=email  

 
cd /scratch/mlinan/  

module load picard/1.135

java -jar  $PICARDPATH/picard.jar CollectAlignmentSummaryMetrics R=slopped.fa I=sorted_IT_EC49.bam O=sorted_IT_EC49.txt 
java -jar  $PICARDPATH/picard.jar CollectAlignmentSummaryMetrics R=slopped.fa I=sorted_IT_EC54.bam O=sorted_IT_EC54.txt 
java -jar  $PICARDPATH/picard.jar CollectAlignmentSummaryMetrics R=slopped.fa I=sorted_IT_EC61.bam O=sorted_IT_EC61.txt 
java -jar  $PICARDPATH/picard.jar CollectAlignmentSummaryMetrics R=slopped.fa I=sorted_IT_EC70.bam O=sorted_IT_EC70.txt 
java -jar  $PICARDPATH/picard.jar CollectAlignmentSummaryMetrics R=slopped.fa I=sorted_IT_EC83.bam O=sorted_IT_EC83.txt 
java -jar  $PICARDPATH/picard.jar CollectAlignmentSummaryMetrics R=slopped.fa I=sorted_IT_EC9.bam O=sorted_IT_EC9.txt 
java -jar  $PICARDPATH/picard.jar CollectAlignmentSummaryMetrics R=slopped.fa I=sorted_IT_FM157.bam O=sorted_IT_FM157.txt 
java -jar  $PICARDPATH/picard.jar CollectAlignmentSummaryMetrics R=slopped.fa I=sorted_IT_FM159.bam O=sorted_IT_FM159.txt 
java -jar  $PICARDPATH/picard.jar CollectAlignmentSummaryMetrics R=slopped.fa I=sorted_IT_FM163.bam O=sorted_IT_FM163.txt 
java -jar  $PICARDPATH/picard.jar CollectAlignmentSummaryMetrics R=slopped.fa I=sorted_IT_FM166.bam O=sorted_IT_FM166.txt 
java -jar  $PICARDPATH/picard.jar CollectAlignmentSummaryMetrics R=slopped.fa I=sorted_IT_TS1.bam O=sorted_IT_TS1.txt 
java -jar  $PICARDPATH/picard.jar CollectAlignmentSummaryMetrics R=slopped.fa I=sorted_IT_TS109.bam O=sorted_IT_TS109.txt 
java -jar  $PICARDPATH/picard.jar CollectAlignmentSummaryMetrics R=slopped.fa I=sorted_IT_TS11.bam O=sorted_IT_TS11.txt 
java -jar  $PICARDPATH/picard.jar CollectAlignmentSummaryMetrics R=slopped.fa I=sorted_IT_TS115.bam O=sorted_IT_TS115.txt 
